# Generated by Django 5.1.1 on 2024-09-16 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rooml'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooml',
            name='type',
            field=models.CharField(choices=[('soloai', 'Adventure'), ('offline', 'Challenge'), ('online', 'multiOn'), ('tournament', 'Tournament')], default='none', max_length=10),
        ),
        migrations.AlterField(
            model_name='rooml',
            name='playerNbr',
            field=models.IntegerField(default=2),
        ),
    ]
