# Generated by Django 5.1.1 on 2024-09-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rooml_type_alter_rooml_playernbr'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('paddle', models.CharField(choices=[('default', 'Default'), ('type1', 'Type 1'), ('type2', 'Type 2')], default='default', max_length=50)),
                ('ball', models.CharField(choices=[('default', 'Default'), ('type1', 'Type 1'), ('type2', 'Type 2')], default='default', max_length=50)),
                ('field', models.CharField(choices=[('default', 'Default'), ('type1', 'Type 1'), ('type2', 'Type 2')], default='default', max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='rooml',
            old_name='type',
            new_name='typel',
        ),
        migrations.CreateModel(
            name='roomData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uniq_id', models.CharField(blank=True, max_length=50, null=True)),
                ('gametype', models.CharField(choices=[('soloai', 'Adventure'), ('offline', 'Challenge'), ('online', 'multiOn'), ('tournament', 'Tournament')], default='offline', max_length=10)),
                ('gamestatue', models.CharField(choices=[('gamestart', 'Game Start'), ('pause', 'Pause'), ('ended', 'Ended'), ('inprogress', 'In Progress')], default='gamestart', max_length=10)),
                ('winning_team', models.CharField(choices=[('tie', 'Tie'), ('blue', 'Blue'), ('red', 'Red')], default='tie', max_length=10)),
                ('max_score', models.IntegerField(default=2)),
                ('redteamScore', models.IntegerField(default=0)),
                ('blueteamScore', models.IntegerField(default=0)),
                ('blueteamplayers', models.ManyToManyField(related_name='blue_team', to='game.playerdata')),
                ('redteamplayers', models.ManyToManyField(related_name='red_team', to='game.playerdata')),
            ],
        ),
    ]
