# Generated by Django 5.1.1 on 2024-09-19 10:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rooml_type_alter_rooml_playernbr'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooml',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rooml',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='game.userl'),
        ),
        migrations.AlterField(
            model_name='rooml',
            name='type',
            field=models.CharField(choices=[('soloai', 'Adventure'), ('offline', 'Challenge'), ('online', 'multiOn'), ('tournament', 'Tournament')], max_length=10),
        ),
    ]
