# Generated by Django 5.1.1 on 2024-10-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playerdata_rename_type_rooml_typel_roomdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomdata',
            old_name='gamestatue',
            new_name='gamestatus',
        ),
    ]
