# Generated by Django 5.1.1 on 2024-10-05 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_gamestatue_roomdata_gamestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='playerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyup', models.CharField(max_length=50)),
                ('keydown', models.CharField(max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='game.playerdata')),
            ],
        ),
    ]
