# Generated by Django 5.1.1 on 2024-10-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_playersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerdata',
            name='keys',
            field=models.JSONField(default=dict),
        ),
    ]
