# Generated by Django 5.1.2 on 2024-10-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_playerdata_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gamesumm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gametype', models.CharField(max_length=50)),
                ('redteam_Score', models.IntegerField(default=0)),
                ('blueteam_Score', models.IntegerField(default=0)),
                ('blueteamp_layers', models.ManyToManyField(related_name='blueteamp_layers', to='game.playerdata')),
                ('redteam_players', models.ManyToManyField(related_name='redteam_players', to='game.playerdata')),
            ],
        ),
    ]
