# Generated by Django 5.1.2 on 2024-10-12 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamesumm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesumm',
            name='blueteamp_layers',
        ),
        migrations.RemoveField(
            model_name='gamesumm',
            name='redteam_players',
        ),
    ]
