# Generated by Django 5.1.2 on 2024-10-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_remove_gamesumm_blueteamp_layers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomdata',
            name='max_score',
            field=models.IntegerField(default=1),
        ),
    ]
