# Generated by Django 5.1.2 on 2024-10-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_roomdata_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesumm',
            name='redteam_players',
            field=models.ManyToManyField(related_name='redteam_players', to='game.playerdata'),
        ),
    ]
