# Generated by Django 5.1.2 on 2024-10-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_gamesumm_redteam_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesumm',
            name='blueteamp_layers',
            field=models.ManyToManyField(related_name='blueteamp_layers', to='game.playerdata'),
        ),
    ]
