# Generated by Django 5.1.2 on 2024-10-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gamesumm_blueteamp_layers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesumm',
            name='blueteamp_layers',
        ),
        migrations.AddField(
            model_name='gamesumm',
            name='blueteamp_players',
            field=models.ManyToManyField(related_name='blueteamp_layers', to='game.playerdata'),
        ),
    ]
